#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Xamarin.ViewPagerIndicatorTest.Resource", IsApplication=true)]

namespace Xamarin.ViewPagerIndicatorTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.centered = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.centered;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.clipPadding = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.clipPadding;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.fadeDelay = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.fadeDelay;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.fadeLength = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.fadeLength;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.fades = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.fades;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.fillColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.fillColor;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.footerColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.footerColor;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.footerIndicatorHeight = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.footerIndicatorHeight;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.footerIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.footerIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.footerIndicatorUnderlinePadding = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.footerIndicatorUnderlinePadding;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.footerLineHeight = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.footerLineHeight;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.footerPadding = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.footerPadding;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.gapWidth = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.gapWidth;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.linePosition = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.linePosition;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.lineWidth = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.lineWidth;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.pageColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.pageColor;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.radius = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.radius;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.selectedBold = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.selectedBold;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.selectedColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.selectedColor;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.snap = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.snap;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.strokeColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.strokeColor;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.strokeWidth = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.strokeWidth;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.titlePadding = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.titlePadding;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.topPadding = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.topPadding;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.unselectedColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.unselectedColor;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.vpiCirclePageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.vpiIconPageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.vpiIconPageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.vpiLinePageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.vpiLinePageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.vpiTabPageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.vpiTabPageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.vpiTitlePageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.vpiTitlePageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Attribute.vpiUnderlinePageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Attribute.vpiUnderlinePageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_centered = global::Xamarin.ViewPagerIndicatorTest.Resource.Boolean.default_circle_indicator_centered;
			global::Xamarin.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_snap = global::Xamarin.ViewPagerIndicatorTest.Resource.Boolean.default_circle_indicator_snap;
			global::Xamarin.ViewPagerIndicator.Resource.Boolean.default_line_indicator_centered = global::Xamarin.ViewPagerIndicatorTest.Resource.Boolean.default_line_indicator_centered;
			global::Xamarin.ViewPagerIndicator.Resource.Boolean.default_title_indicator_selected_bold = global::Xamarin.ViewPagerIndicatorTest.Resource.Boolean.default_title_indicator_selected_bold;
			global::Xamarin.ViewPagerIndicator.Resource.Boolean.default_underline_indicator_fades = global::Xamarin.ViewPagerIndicatorTest.Resource.Boolean.default_underline_indicator_fades;
			global::Xamarin.ViewPagerIndicator.Resource.Color.default_circle_indicator_fill_color = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.default_circle_indicator_fill_color;
			global::Xamarin.ViewPagerIndicator.Resource.Color.default_circle_indicator_page_color = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.default_circle_indicator_page_color;
			global::Xamarin.ViewPagerIndicator.Resource.Color.default_circle_indicator_stroke_color = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.default_circle_indicator_stroke_color;
			global::Xamarin.ViewPagerIndicator.Resource.Color.default_line_indicator_selected_color = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.default_line_indicator_selected_color;
			global::Xamarin.ViewPagerIndicator.Resource.Color.default_line_indicator_unselected_color = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.default_line_indicator_unselected_color;
			global::Xamarin.ViewPagerIndicator.Resource.Color.default_title_indicator_footer_color = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.default_title_indicator_footer_color;
			global::Xamarin.ViewPagerIndicator.Resource.Color.default_title_indicator_selected_color = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.default_title_indicator_selected_color;
			global::Xamarin.ViewPagerIndicator.Resource.Color.default_title_indicator_text_color = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.default_title_indicator_text_color;
			global::Xamarin.ViewPagerIndicator.Resource.Color.default_underline_indicator_selected_color = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.default_underline_indicator_selected_color;
			global::Xamarin.ViewPagerIndicator.Resource.Color.vpi__background_holo_dark = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.vpi__background_holo_dark;
			global::Xamarin.ViewPagerIndicator.Resource.Color.vpi__background_holo_light = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.vpi__background_holo_light;
			global::Xamarin.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::Xamarin.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::Xamarin.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_dark = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.vpi__bright_foreground_holo_dark;
			global::Xamarin.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_light = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.vpi__bright_foreground_holo_light;
			global::Xamarin.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::Xamarin.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::Xamarin.ViewPagerIndicator.Resource.Color.vpi__dark_theme = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.vpi__dark_theme;
			global::Xamarin.ViewPagerIndicator.Resource.Color.vpi__light_theme = global::Xamarin.ViewPagerIndicatorTest.Resource.Color.vpi__light_theme;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_radius = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_circle_indicator_radius;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_stroke_width = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_circle_indicator_stroke_width;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_line_indicator_gap_width = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_line_indicator_gap_width;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_line_indicator_line_width = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_line_indicator_line_width;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_line_indicator_stroke_width = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_line_indicator_stroke_width;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_title_indicator_clip_padding = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_title_indicator_clip_padding;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_height = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_title_indicator_footer_indicator_height;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_line_height = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_title_indicator_footer_line_height;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_padding = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_title_indicator_footer_padding;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_title_indicator_text_size = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_title_indicator_text_size;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_title_indicator_title_padding = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_title_indicator_title_padding;
			global::Xamarin.ViewPagerIndicator.Resource.Dimension.default_title_indicator_top_padding = global::Xamarin.ViewPagerIndicatorTest.Resource.Dimension.default_title_indicator_top_padding;
			global::Xamarin.ViewPagerIndicator.Resource.Drawable.vpi__tab_indicator = global::Xamarin.ViewPagerIndicatorTest.Resource.Drawable.vpi__tab_indicator;
			global::Xamarin.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_focused_holo = global::Xamarin.ViewPagerIndicatorTest.Resource.Drawable.vpi__tab_selected_focused_holo;
			global::Xamarin.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_holo = global::Xamarin.ViewPagerIndicatorTest.Resource.Drawable.vpi__tab_selected_holo;
			global::Xamarin.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_pressed_holo = global::Xamarin.ViewPagerIndicatorTest.Resource.Drawable.vpi__tab_selected_pressed_holo;
			global::Xamarin.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_focused_holo = global::Xamarin.ViewPagerIndicatorTest.Resource.Drawable.vpi__tab_unselected_focused_holo;
			global::Xamarin.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_holo = global::Xamarin.ViewPagerIndicatorTest.Resource.Drawable.vpi__tab_unselected_holo;
			global::Xamarin.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_pressed_holo = global::Xamarin.ViewPagerIndicatorTest.Resource.Drawable.vpi__tab_unselected_pressed_holo;
			global::Xamarin.ViewPagerIndicator.Resource.Id.bottom = global::Xamarin.ViewPagerIndicatorTest.Resource.Id.bottom;
			global::Xamarin.ViewPagerIndicator.Resource.Id.none = global::Xamarin.ViewPagerIndicatorTest.Resource.Id.none;
			global::Xamarin.ViewPagerIndicator.Resource.Id.top = global::Xamarin.ViewPagerIndicatorTest.Resource.Id.top;
			global::Xamarin.ViewPagerIndicator.Resource.Id.triangle = global::Xamarin.ViewPagerIndicatorTest.Resource.Id.triangle;
			global::Xamarin.ViewPagerIndicator.Resource.Id.underline = global::Xamarin.ViewPagerIndicatorTest.Resource.Id.underline;
			global::Xamarin.ViewPagerIndicator.Resource.Integer.default_circle_indicator_orientation = global::Xamarin.ViewPagerIndicatorTest.Resource.Integer.default_circle_indicator_orientation;
			global::Xamarin.ViewPagerIndicator.Resource.Integer.default_title_indicator_footer_indicator_style = global::Xamarin.ViewPagerIndicatorTest.Resource.Integer.default_title_indicator_footer_indicator_style;
			global::Xamarin.ViewPagerIndicator.Resource.Integer.default_title_indicator_line_position = global::Xamarin.ViewPagerIndicatorTest.Resource.Integer.default_title_indicator_line_position;
			global::Xamarin.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_delay = global::Xamarin.ViewPagerIndicatorTest.Resource.Integer.default_underline_indicator_fade_delay;
			global::Xamarin.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_length = global::Xamarin.ViewPagerIndicatorTest.Resource.Integer.default_underline_indicator_fade_length;
			global::Xamarin.ViewPagerIndicator.Resource.Style.TextAppearance_TabPageIndicator = global::Xamarin.ViewPagerIndicatorTest.Resource.Style.TextAppearance_TabPageIndicator;
			global::Xamarin.ViewPagerIndicator.Resource.Style.Theme_PageIndicatorDefaults = global::Xamarin.ViewPagerIndicatorTest.Resource.Style.Theme_PageIndicatorDefaults;
			global::Xamarin.ViewPagerIndicator.Resource.Style.Widget = global::Xamarin.ViewPagerIndicatorTest.Resource.Style.Widget;
			global::Xamarin.ViewPagerIndicator.Resource.Style.Widget_IconPageIndicator = global::Xamarin.ViewPagerIndicatorTest.Resource.Style.Widget_IconPageIndicator;
			global::Xamarin.ViewPagerIndicator.Resource.Style.Widget_TabPageIndicator = global::Xamarin.ViewPagerIndicatorTest.Resource.Style.Widget_TabPageIndicator;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.CirclePageIndicator;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_background = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.CirclePageIndicator_android_background;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_orientation = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.CirclePageIndicator_android_orientation;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_centered = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.CirclePageIndicator_centered;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_fillColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.CirclePageIndicator_fillColor;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_pageColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.CirclePageIndicator_pageColor;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_radius = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.CirclePageIndicator_radius;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_snap = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.CirclePageIndicator_snap;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.CirclePageIndicator_strokeColor;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeWidth = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.CirclePageIndicator_strokeWidth;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.LinePageIndicator = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.LinePageIndicator;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_android_background = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.LinePageIndicator_android_background;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_centered = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.LinePageIndicator_centered;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_gapWidth = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.LinePageIndicator_gapWidth;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_lineWidth = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.LinePageIndicator_lineWidth;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_selectedColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.LinePageIndicator_selectedColor;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_strokeWidth = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.LinePageIndicator_strokeWidth;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_unselectedColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.LinePageIndicator_unselectedColor;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_background = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_android_background;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_android_textColor;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textSize = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_android_textSize;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_clipPadding = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_clipPadding;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_footerColor;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerLineHeight = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_footerLineHeight;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerPadding = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_footerPadding;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_linePosition = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_linePosition;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedBold = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_selectedBold;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_selectedColor;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_titlePadding = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_titlePadding;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_topPadding = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.TitlePageIndicator_topPadding;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.UnderlinePageIndicator;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_android_background = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.UnderlinePageIndicator_android_background;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeDelay = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.UnderlinePageIndicator_fadeDelay;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeLength = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.UnderlinePageIndicator_fadeLength;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fades = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.UnderlinePageIndicator_fades;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_selectedColor = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.UnderlinePageIndicator_selectedColor;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.ViewPagerIndicator;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle;
			global::Xamarin.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = global::Xamarin.ViewPagerIndicatorTest.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int centered = 2130771974;
			
			// aapt resource value: 0x7f010011
			public const int clipPadding = 2130771985;
			
			// aapt resource value: 0x7f01001d
			public const int fadeDelay = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int fadeLength = 2130771998;
			
			// aapt resource value: 0x7f01001c
			public const int fades = 2130771996;
			
			// aapt resource value: 0x7f01000a
			public const int fillColor = 2130771978;
			
			// aapt resource value: 0x7f010012
			public const int footerColor = 2130771986;
			
			// aapt resource value: 0x7f010015
			public const int footerIndicatorHeight = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int footerIndicatorStyle = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int footerIndicatorUnderlinePadding = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int footerLineHeight = 2130771987;
			
			// aapt resource value: 0x7f010017
			public const int footerPadding = 2130771991;
			
			// aapt resource value: 0x7f010010
			public const int gapWidth = 2130771984;
			
			// aapt resource value: 0x7f010018
			public const int linePosition = 2130771992;
			
			// aapt resource value: 0x7f01000f
			public const int lineWidth = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int pageColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int radius = 2130771980;
			
			// aapt resource value: 0x7f010019
			public const int selectedBold = 2130771993;
			
			// aapt resource value: 0x7f010007
			public const int selectedColor = 2130771975;
			
			// aapt resource value: 0x7f01000d
			public const int snap = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int strokeColor = 2130771982;
			
			// aapt resource value: 0x7f010008
			public const int strokeWidth = 2130771976;
			
			// aapt resource value: 0x7f01001a
			public const int titlePadding = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int topPadding = 2130771995;
			
			// aapt resource value: 0x7f010009
			public const int unselectedColor = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int vpiIconPageIndicatorStyle = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int vpiLinePageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int vpiTabPageIndicatorStyle = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int vpiTitlePageIndicatorStyle = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int vpiUnderlinePageIndicatorStyle = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int default_circle_indicator_centered = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int default_circle_indicator_snap = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int default_line_indicator_centered = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int default_title_indicator_selected_bold = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int default_underline_indicator_fades = 2131099652;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int default_circle_indicator_fill_color = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int default_circle_indicator_page_color = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int default_circle_indicator_stroke_color = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int default_line_indicator_selected_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int default_line_indicator_unselected_color = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int default_title_indicator_footer_color = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int default_title_indicator_selected_color = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int default_title_indicator_text_color = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int default_underline_indicator_selected_color = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int vpi__background_holo_dark = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int vpi__background_holo_light = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int vpi__bright_foreground_disabled_holo_dark = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int vpi__bright_foreground_disabled_holo_light = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int vpi__bright_foreground_holo_dark = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int vpi__bright_foreground_holo_light = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int vpi__bright_foreground_inverse_holo_dark = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int vpi__bright_foreground_inverse_holo_light = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int vpi__dark_theme = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int vpi__light_theme = 2131034130;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_radius = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_circle_indicator_stroke_width = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int default_line_indicator_gap_width = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int default_line_indicator_line_width = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int default_line_indicator_stroke_width = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int default_title_indicator_clip_padding = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int default_title_indicator_footer_indicator_height = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int default_title_indicator_footer_indicator_underline_padding = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int default_title_indicator_footer_line_height = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int default_title_indicator_footer_padding = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int default_title_indicator_text_size = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int default_title_indicator_title_padding = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int default_title_indicator_top_padding = 2131230732;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int vpi__tab_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int vpi__tab_selected_focused_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int vpi__tab_selected_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int vpi__tab_selected_pressed_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int vpi__tab_unselected_focused_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int vpi__tab_unselected_holo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int vpi__tab_unselected_pressed_holo = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0003
			public const int bottom = 2131427331;
			
			// aapt resource value: 0x7f0b0007
			public const int indicator = 2131427335;
			
			// aapt resource value: 0x7f0b0000
			public const int none = 2131427328;
			
			// aapt resource value: 0x7f0b0006
			public const int pager = 2131427334;
			
			// aapt resource value: 0x7f0b0005
			public const int section_label = 2131427333;
			
			// aapt resource value: 0x7f0b0004
			public const int top = 2131427332;
			
			// aapt resource value: 0x7f0b0001
			public const int triangle = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int underline = 2131427330;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_orientation = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_title_indicator_footer_indicator_style = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_title_indicator_line_position = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int default_underline_indicator_fade_delay = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int default_underline_indicator_fade_length = 2131165188;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int fragment_main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a0000
			public const int app_name = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int section_format = 2131361793;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_TabPageIndicator = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int Theme_PageIndicatorDefaults = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int Widget = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int Widget_IconPageIndicator = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int Widget_TabPageIndicator = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[]
			{
					16842948,
					16842964,
					2130771974,
					2130771976,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public const int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public const int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] LinePageIndicator = new int[]
			{
					16842964,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771983,
					2130771984};
			
			// aapt resource value: 0
			public const int LinePageIndicator_android_background = 0;
			
			// aapt resource value: 1
			public const int LinePageIndicator_centered = 1;
			
			// aapt resource value: 6
			public const int LinePageIndicator_gapWidth = 6;
			
			// aapt resource value: 5
			public const int LinePageIndicator_lineWidth = 5;
			
			// aapt resource value: 2
			public const int LinePageIndicator_selectedColor = 2;
			
			// aapt resource value: 3
			public const int LinePageIndicator_strokeWidth = 3;
			
			// aapt resource value: 4
			public const int LinePageIndicator_unselectedColor = 4;
			
			public static int[] TitlePageIndicator = new int[]
			{
					16842901,
					16842904,
					16842964,
					2130771975,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995};
			
			// aapt resource value: 2
			public const int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public const int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public const int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public const int TitlePageIndicator_topPadding = 14;
			
			public static int[] UnderlinePageIndicator = new int[]
			{
					16842964,
					2130771975,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 0
			public const int UnderlinePageIndicator_android_background = 0;
			
			// aapt resource value: 3
			public const int UnderlinePageIndicator_fadeDelay = 3;
			
			// aapt resource value: 4
			public const int UnderlinePageIndicator_fadeLength = 4;
			
			// aapt resource value: 2
			public const int UnderlinePageIndicator_fades = 2;
			
			// aapt resource value: 1
			public const int UnderlinePageIndicator_selectedColor = 1;
			
			public static int[] ViewPagerIndicator = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
